import type { Ability, CharacterClass, Gender, Interactable, Race } from '@game/engine';

/**
 * Every text of the engine that the player reads, in one place. Do not put a user-facing text in
 * another file: add it here, so a translation later is one file. What things say is not here:
 * that is content, and each world brings its own (WorldDefinition.examine, fixture content).
 */
export const STRINGS = {
  hintKeyboard: 'WASD or arrow keys to move · E to act',
  hintKeyboardFight: 'WASD or arrow keys to move · E to act · Space to attack',
  attack: 'Attack',
  hintTouch: 'Touch and drag anywhere to move',
  doorBlocked: 'Step out of the doorway first.',
  doorBlockedByOther: 'Someone is in the doorway.',
  actionLabel: 'Act',
  openDoor: 'Open the door',
  closeDoor: 'Close the door',
  examine: (name: string): string => `Examine the ${name}`,
  talk: 'Talk',
  next: 'Next',
  close: 'Close',
  lookIntoPortal: 'Look into the portal',
  /** The names of things in action labels ("Examine the map table"). */
  names: {
    tree: 'tree',
    rock: 'rock',
    door: 'door',
    bookshelf: 'bookshelf',
    table: 'table',
    bed: 'bed',
    chest: 'chest',
    barrel: 'barrel',
    lectern: 'lectern',
    desk: 'desk',
    anvil: 'anvil',
    maptable: 'map table',
    boardtable: 'game board',
    mirror: 'mirror',
    apothecary: 'cabinet',
    coinchest: 'strongbox',
    noticeboard: 'notice board',
    lamppost: 'lamp',
    fountain: 'fountain',
    portal: 'portal',
    npc: 'stranger',
    rug: 'rug',
    crate: 'crate',
    cauldron: 'cauldron',
    telescope: 'telescope',
    candelabra: 'candelabra',
    forge: 'forge',
    crystalball: 'crystal ball',
    scales: 'scales',
  } satisfies Record<Interactable, string>,
  linkClose: 'Close',
  linkKeyHint: 'or press E',
  /** The "You" section of the settings: the character that the visitor plays. */
  you: {
    heading: 'You',
    guest: 'A guest: nothing is saved',
    mainMenu: 'Main menu',
    signOut: 'Sign out',
  },
  /** The menu before the game: sign-in, new game, continue, and the character builder. */
  menu: {
    newGame: 'New game',
    continue: 'Continue',
    signedIn: (via: 'google' | 'dev'): string => (via === 'google' ? 'Signed in with Google' : 'Signed in (development)'),
    signOut: 'Sign out',
    deleteAccount: 'Delete account',
    deleteAccountAsk: 'Delete your account and all your characters? This cannot be undone.',
    deleteAccountYes: 'Delete everything',
    privacy: 'Privacy',
    signInTitle: 'Sign in to keep your characters',
    google: 'Sign in with Google',
    devName: 'Name',
    devSignIn: 'Dev sign-in',
    noSignIn: 'Sign-in is not available now. Try again later.',
    loginFailed: 'The sign-in did not work. Try again.',
    loginCancelled: 'The sign-in was cancelled.',
    serverDown: 'The server does not answer. Try again in a moment.',
    failed: 'Something went wrong. Try again.',
    retry: 'Try again',
    loading: 'Loading…',
    back: 'Back',
    next: 'Next',
    create: 'Create',
    creating: 'Creating…',
    starting: 'Into the wilds…',
    continueTitle: 'Choose a character',
    noCharacters: 'You have no characters yet.',
    lastPlayed: (when: string): string => `Last played ${when}`,
    created: (when: string): string => `Created ${when}`,
    delete: 'Delete',
    deleteAsk: (name: string): string => `Delete ${name}? This cannot be undone.`,
    keep: 'Keep',
    limit: (n: number): string => `You have ${n} characters, the most there can be. Delete one to make another.`,
    newTitle: 'A new character',
    step: (i: number, n: number, name: string): string => `Step ${i} of ${n}: ${name}`,
    appearance: 'Appearance',
    abilities: 'Abilities',
    race: 'Race',
    class: 'Class',
    gender: 'Gender',
    name: 'Name',
    namePlaceholder: 'Your name',
    nameHint: 'Everyone sees it over your head (2 to 16 letters).',
    randomName: 'Random name',
    anotherLook: 'Another look',
    drawing: 'Drawing…',
    pointsLeft: (n: number): string => (n === 1 ? '1 point left' : `${n} points left`),
    pointsHelp: 'Every ability starts at 8 and can go up to 15. Each step up to 13 costs 1 point; 14 and 15 cost 2 points each.',
    primary: (names: string): string => `Your class needs ${names} most.`,
    halfElf: 'As a half-elf, choose two abilities other than Charisma for +1.',
    raise: (ability: string): string => `Raise ${ability}`,
    lower: (ability: string): string => `Lower ${ability}`,
    choose: (ability: string): string => `+1 to ${ability}`,
    reset: 'Reset',
    columns: { ability: 'Ability', base: 'Base', race: 'Race', total: 'Score', mod: 'Mod' },
    unspent: (n: number): string => `You still have ${n === 1 ? '1 point' : `${n} points`} to spend.`,
    chooseTwo: 'Choose two abilities for the half-elf +1.',
  },
  races: {
    human: { name: 'Human', line: 'Adaptable and driven, found everywhere.' },
    dwarf: { name: 'Dwarf', line: 'Short, stout and stubborn as stone.' },
    elf: { name: 'Elf', line: 'Graceful, keen-eyed and long-lived.' },
    gnome: { name: 'Gnome', line: 'Small, curious and full of energy.' },
    'half-elf': { name: 'Half-Elf', line: 'At home in two worlds, and in neither.' },
    halfling: { name: 'Halfling', line: 'Small, nimble and very lucky.' },
    'half-orc': { name: 'Half-Orc', line: 'Strong, fierce and hard to stop.' },
  } satisfies Record<Race, { name: string; line: string }>,
  classes: {
    barbarian: { name: 'Barbarian', line: 'A fierce warrior of primal rage.' },
    bard: { name: 'Bard', line: 'A performer whose songs work magic.' },
    cleric: { name: 'Cleric', line: 'A priest who wields divine power.' },
    druid: { name: 'Druid', line: 'A keeper of the old ways of nature.' },
    fighter: { name: 'Fighter', line: 'A master of weapons and armour.' },
    monk: { name: 'Monk', line: 'A fighter of trained body and spirit.' },
    paladin: { name: 'Paladin', line: 'A holy knight bound by an oath.' },
    ranger: { name: 'Ranger', line: 'A hunter and tracker of the wilds.' },
    rogue: { name: 'Rogue', line: 'A scoundrel of stealth and tricks.' },
    sorcerer: { name: 'Sorcerer', line: 'A caster with magic in the blood.' },
    warlock: { name: 'Warlock', line: 'A seeker bound to an otherworldly patron.' },
    wizard: { name: 'Wizard', line: 'A scholar of the arcane arts.' },
  } satisfies Record<CharacterClass, { name: string; line: string }>,
  genders: { male: 'Male', female: 'Female', undetermined: 'Undetermined' } satisfies Record<Gender, string>,
  abilities: {
    str: { name: 'Strength', short: 'STR' },
    dex: { name: 'Dexterity', short: 'DEX' },
    con: { name: 'Constitution', short: 'CON' },
    int: { name: 'Intelligence', short: 'INT' },
    wis: { name: 'Wisdom', short: 'WIS' },
    cha: { name: 'Charisma', short: 'CHA' },
  } satisfies Record<Ability, { name: string; short: string }>,
  worlds: 'Worlds',
  worldsCurrent: 'you are here',
  /** The presence label of a shared (multiplayer) world. */
  presence: {
    connecting: 'Looking for other visitors…',
    alone: 'You are the only visitor here',
    others: (n: number): string => (n === 1 ? '1 other visitor here' : `${n} other visitors here`),
    offline: 'No connection: you see no other visitors',
    version: 'The game has changed: reload the page to see other visitors',
    full: 'The world is full: you are alone in your copy',
    busy: 'Too many open tabs: this one is alone',
    world: 'This world is not shared now',
    account: 'Sign in to see other visitors',
  },
} as const;
