import type { Ability, CharacterClass, Gender, Interactable, ItemKind, Race } from '@game/engine';

/**
 * Every text of the engine that the player reads, in one place. Do not put a user-facing text in
 * another file: add it here, so a translation later is one file. What things say is not here:
 * that is content, and each world brings its own (WorldDefinition.examine, fixture content).
 */
export const STRINGS = {
  hintKeyboard: 'WASD or arrow keys to move · E to act',
  hintKeyboardFight: 'WASD or arrow keys to move · E to act · Click to attack · Shift to roll · C to sneak',
  attack: 'Attack',
  dodge: 'Roll',
  hintTouch: 'Touch and drag anywhere to move',
  doorBlocked: 'Step out of the doorway first.',
  doorBlockedByOther: 'Someone is in the doorway.',
  actionLabel: 'Act',
  openDoor: 'Open the door',
  closeDoor: 'Close the door',
  /** The label for the door of a building that is shut for good, or barred for a weak character. */
  tryDoor: 'Try the door',
  /** A barred door (Building.barred): the label for a character strong enough, and what the player says. */
  forceDoor: 'Force the door',
  barred: 'Boards are nailed across it. I am not strong enough to break them.',
  forced: 'The boards break.',
  /** A chest that gives loot (loot.ts), and what the player says when it opens it. */
  openChest: 'Open the chest',
  /** A chest with a lock (Fixture.lock): the label for a character with the Dexterity to pick it, and the lines. */
  pickLock: 'Pick the lock',
  /** A patch of herbs and a buried cache (Wisdom: they show only close by). */
  gather: 'Gather the herbs',
  dig: 'Dig here',
  herbsGone: 'Somebody picked them. They will grow again.',
  cacheGone: 'Somebody dug it up before me.',
  dug: 'I dig up a small box.',
  picked: 'The lock clicks open.',
  locked: 'It is locked. I cannot pick it.',
  chestEmpty: 'It is empty.',
  packFull: 'My pack is full.',
  /** A chest in a shared world while the connection is down: the server decides what is in it. */
  chestOffline: 'I cannot open it now. No connection.',
  found: (things: string): string => `I find ${things}.`,
  coins: (n: number): string => (n === 1 ? '1 coin' : `${n} coins`),
  /** An item: with an article ("a silver ring"), and the plural ("silver rings"). */
  items: {
    'imp-horn': { a: 'an imp horn', many: 'imp horns' },
    'brute-tusk': { a: 'a brute tusk', many: 'brute tusks' },
    candle: { a: 'a candle stub', many: 'candle stubs' },
    ring: { a: 'a silver ring', many: 'silver rings' },
    cup: { a: 'a pewter cup', many: 'pewter cups' },
    herbs: { a: 'a bundle of herbs', many: 'bundles of herbs' },
    draught: { a: 'a healing draught', many: 'healing draughts' },
    antidote: { a: 'an antidote', many: 'antidotes' },
    'strong-draught': { a: 'a strong draught', many: 'strong draughts' },
  } satisfies Record<ItemKind, { a: string; many: string }>,
  /** A drink from the pack (items.ts, DRINKS): what the player says. */
  drank: {
    draught: 'The draught is bitter. The wound closes a little.',
    antidote: 'The antidote burns. The poison is gone.',
    'strong-draught': 'The strong draught burns all the way down. I feel whole.',
    herbs: 'I chew the bitter leaves. I feel a little better.',
  } as Readonly<Partial<Record<ItemKind, string>>>,
  /** Lore that the player cannot read yet (Interaction.lore, a score 1 or 2 under the gate). */
  loreHint: (tag: string): string => `${tag} There is more here, but I cannot make sense of it.`,
  /** A barred door or a locked chest without the score: with a clue of the gate, or without (gateView). */
  barredPlain: 'Boards are nailed across it.',
  lockedPlain: 'It is locked.',
  /** The map panel (ui/map-panel.ts). */
  map: {
    button: 'Map',
    heading: 'Map',
    note: 'What you have seen of the land.',
    alone: 'Played alone: the map is not saved.',
  },
  /** The vitals (ui/vitals.ts): hit points, stamina, effects. */
  vitals: {
    hp: (hp: number, max: number): string => `${hp} of ${max} hit points`,
    poisoned: 'Poisoned',
    drunk: 'Drunk',
  },
  /** A bed of the player's own (Interaction.rest). */
  rest: 'Rest',
  rested: 'I rest a while. I feel well again.',
  /** After a defeat: where the player wakes, and what it lost. */
  woke: 'I wake up, sore and alive.',
  wokeLost: (coins: number): string => `I wake up, sore and alive. ${coins === 1 ? 'A coin is' : `${coins} coins are`} gone.`,
  /** The player comes into a refuge (WorldSource.refuges) for the first time. */
  refuge: 'This place feels safe. If I fall, I can wake here.',
  /** The pack panel (ui/pack-panel.ts). */
  pack: {
    button: 'Pack',
    /** The tooltip of the button: the key that opens the pack too. */
    buttonKey: 'Pack (I)',
    heading: 'Pack',
    coins: 'Coins',
    slots: (used: number, all: number): string => `${used} of ${all} slots`,
    empty: 'Your pack is empty.',
    guest: 'A guest: what you find is not saved.',
    drink: (what: string, slot: number): string => `Drink ${what} (${slot})`,
    chew: (what: string, slot: number): string => `Chew ${what} (${slot})`,
    chewHint: (what: string): string => `You could chew ${what}, if you knew more of herbs.`,
    offline: 'Played alone: what you find here is not saved.',
  },
  /** What the scores give (ui/traits-list.ts): in the builder and in the "You" section. */
  traits: {
    heading: 'What your scores give',
    damage: 'Damage of a blow',
    damageValue: (n: number, ability: string): string => `${n} (${ability})`,
    push: 'Knockback',
    stagger: 'Stagger',
    share: (share: number): string => (Math.abs(share - 1) < 0.005 ? 'normal' : `${share > 1 ? '+' : '−'}${Math.round(Math.abs(share - 1) * 100)}%`),
    slots: 'Pack',
    slotsValue: (n: number): string => `${n} slots`,
    wade: 'Shallow water',
    force: 'Barred doors',
    attacks: 'Attacks',
    attacksValue: (seconds: number): string => `one every ${seconds.toFixed(2)} s`,
    guard: 'Guard after a hit',
    seconds: (seconds: number): string => `${seconds.toFixed(2)} s`,
    dodge: 'Roll',
    dodgeValue: (seconds: number): string => `every ${seconds.toFixed(2)} s`,
    sight: 'Mobs see you from',
    sightValue: (share: number, sneaking: number): string => `${Math.round(share * 100)}% (sneaking ${Math.round(sneaking * 100)}%)`,
    range: 'Arrows fly',
    rangeValue: (tiles: number): string => `${tiles} tiles`,
    pick: 'Locked chests',
    pickYes: 'you pick them',
    hp: 'Hit points',
    stun: 'Stun from a hit',
    recover: 'A hit point back',
    recoverValue: (seconds: number): string => `every ${seconds.toFixed(0)} s`,
    stamina: 'Stamina',
    staminaValue: (max: number, refill: number): string => `${max} (${refill} back each second)`,
    resist: 'Poison and drink',
    opening: 'A blow on a wind-up',
    openingValue: (n: number): string => (n > 0 ? `+${n} damage` : 'no bonus'),
    readFoe: 'Read a mob',
    readFoeHealth: 'its health',
    readFoeOpening: 'its health and its wind-up',
    map: 'The map',
    mapValue: (int: number): string => (int >= 15 ? 'barred houses and locked chests' : int >= 13 ? 'names and refuges' : int >= 11 ? 'houses' : 'the ground'),
    lore: 'Old writing',
    loreYes: 'you read it',
    sense: 'Sense a mob that hunts you',
    seek: 'See hidden things',
    tiles: (n: number): string => (n === 1 ? '1 tile' : `${n} tiles`),
    night: 'The night',
    nightValue: (share: number): string =>
      share < 1 ? `${Math.round((1 - share) * 100)}% lighter` : share > 1 ? `${Math.round((share - 1) * 100)}% darker` : 'normal',
    insight: 'Insight',
    insightYes: 'you see what people hide',
    medicine: 'Medicine',
    medicineYes: 'chew herbs for a hit point',
    homeward: 'The way home',
    homewardYes: 'an arrow points to it',
    from: (ability: string, min: number): string => `from ${ability} ${min}`,
    wadeYes: 'you wade through it',
    forceYes: 'you break them',
  },
  readSign: 'Read the sign',
  examine: (name: string): string => `Examine the ${name}`,
  talk: 'Talk',
  next: 'Next',
  close: 'Close',
  lookIntoPortal: 'Look into the portal',
  /** The conversation panel (ui/conversation.ts). */
  conversation: {
    end: 'End the conversation',
    /** The action button while the NPC says its first line: the answers come next. */
    answer: 'Answer',
    you: 'You',
    keys: '↑ ↓ to choose · E to answer · Esc to leave',
  },
  /** The names of things in action labels ("Examine the map table"). */
  names: {
    tree: 'tree',
    rock: 'rock',
    door: 'door',
    bookshelf: 'bookshelf',
    table: 'table',
    bed: 'bed',
    chest: 'chest',
    barrel: 'barrel',
    lectern: 'lectern',
    desk: 'desk',
    anvil: 'anvil',
    maptable: 'map table',
    boardtable: 'game board',
    mirror: 'mirror',
    apothecary: 'cabinet',
    coinchest: 'strongbox',
    noticeboard: 'notice board',
    lamppost: 'lamp',
    fountain: 'fountain',
    portal: 'portal',
    npc: 'stranger',
    rug: 'rug',
    crate: 'crate',
    cauldron: 'cauldron',
    telescope: 'telescope',
    candelabra: 'candelabra',
    forge: 'forge',
    crystalball: 'crystal ball',
    scales: 'scales',
    signpost: 'signpost',
    herbpatch: 'herbs',
    cache: 'dug earth',
  } satisfies Record<Interactable, string>,
  linkClose: 'Close',
  linkKeyHint: 'or press E',
  /** The "You" section of the settings: the character that the visitor plays. */
  you: {
    heading: 'You',
    guest: 'A guest: nothing is saved',
    mainMenu: 'Main menu',
    signOut: 'Sign out',
  },
  /** The menu before the game: sign-in, new game, continue, and the character builder. */
  menu: {
    newGame: 'New game',
    continue: 'Continue',
    signedIn: (via: 'google' | 'dev'): string => (via === 'google' ? 'Signed in with Google' : 'Signed in (development)'),
    signOut: 'Sign out',
    deleteAccount: 'Delete account',
    deleteAccountAsk: 'Delete your account and all your characters? This cannot be undone.',
    deleteAccountYes: 'Delete everything',
    privacy: 'Privacy',
    signInTitle: 'Sign in to keep your characters',
    google: 'Sign in with Google',
    devName: 'Name or email',
    devSignIn: 'Dev sign-in',
    noSignIn: 'Sign-in is not available now. Try again later.',
    loginFailed: 'The sign-in did not work. Try again.',
    loginCancelled: 'The sign-in was cancelled.',
    loginElsewhere: 'You signed in on another device, so this one was signed out. Sign in again to play here.',
    serverDown: 'The server does not answer. Try again in a moment.',
    failed: 'Something went wrong. Try again.',
    retry: 'Try again',
    loading: 'Loading…',
    back: 'Back',
    next: 'Next',
    create: 'Create',
    creating: 'Creating…',
    starting: 'Into the wilds…',
    continueTitle: 'Choose a character',
    noCharacters: 'You have no characters yet.',
    lastPlayed: (when: string): string => `Last played ${when}`,
    created: (when: string): string => `Created ${when}`,
    delete: 'Delete',
    deleteAsk: (name: string): string => `Delete ${name}? This cannot be undone.`,
    keep: 'Keep',
    limit: (n: number): string => `You have ${n} characters, the most there can be. Delete one to make another.`,
    newTitle: 'A new character',
    step: (i: number, n: number, name: string): string => `Step ${i} of ${n}: ${name}`,
    appearance: 'Appearance',
    abilities: 'Abilities',
    race: 'Race',
    class: 'Class',
    gender: 'Gender',
    name: 'Name',
    namePlaceholder: 'Your name',
    nameHint: 'Everyone sees it over your head (2 to 16 letters).',
    randomName: 'Random name',
    anotherLook: 'Another look',
    drawing: 'Drawing…',
    pointsLeft: (n: number): string => (n === 1 ? '1 point left' : `${n} points left`),
    pointsHelp: 'Every ability starts at 8 and can go up to 15. Each step up to 13 costs 1 point; 14 and 15 cost 2 points each.',
    primary: (names: string): string => `Your class needs ${names} most.`,
    halfElf: 'As a half-elf, choose two abilities other than Charisma for +1.',
    raise: (ability: string): string => `Raise ${ability}`,
    lower: (ability: string): string => `Lower ${ability}`,
    choose: (ability: string): string => `+1 to ${ability}`,
    reset: 'Reset',
    columns: { ability: 'Ability', base: 'Base', race: 'Race', total: 'Score', mod: 'Mod' },
    unspent: (n: number): string => `You still have ${n === 1 ? '1 point' : `${n} points`} to spend.`,
    chooseTwo: 'Choose two abilities for the half-elf +1.',
  },
  races: {
    human: { name: 'Human', line: 'Adaptable and driven, found everywhere.' },
    dwarf: { name: 'Dwarf', line: 'Short, stout and stubborn as stone.' },
    elf: { name: 'Elf', line: 'Graceful, keen-eyed and long-lived.' },
    gnome: { name: 'Gnome', line: 'Small, curious and full of energy.' },
    'half-elf': { name: 'Half-Elf', line: 'At home in two worlds, and in neither.' },
    halfling: { name: 'Halfling', line: 'Small, nimble and very lucky.' },
    'half-orc': { name: 'Half-Orc', line: 'Strong, fierce and hard to stop.' },
  } satisfies Record<Race, { name: string; line: string }>,
  classes: {
    barbarian: { name: 'Barbarian', line: 'A fierce warrior of primal rage.' },
    bard: { name: 'Bard', line: 'A performer whose songs work magic.' },
    cleric: { name: 'Cleric', line: 'A priest who wields divine power.' },
    druid: { name: 'Druid', line: 'A keeper of the old ways of nature.' },
    fighter: { name: 'Fighter', line: 'A master of weapons and armour.' },
    monk: { name: 'Monk', line: 'A fighter of trained body and spirit.' },
    paladin: { name: 'Paladin', line: 'A holy knight bound by an oath.' },
    ranger: { name: 'Ranger', line: 'A hunter and tracker of the wilds.' },
    rogue: { name: 'Rogue', line: 'A scoundrel of stealth and tricks.' },
    sorcerer: { name: 'Sorcerer', line: 'A caster with magic in the blood.' },
    warlock: { name: 'Warlock', line: 'A seeker bound to an otherworldly patron.' },
    wizard: { name: 'Wizard', line: 'A scholar of the arcane arts.' },
  } satisfies Record<CharacterClass, { name: string; line: string }>,
  genders: { male: 'Male', female: 'Female', undetermined: 'Undetermined' } satisfies Record<Gender, string>,
  abilities: {
    str: { name: 'Strength', short: 'STR' },
    dex: { name: 'Dexterity', short: 'DEX' },
    con: { name: 'Constitution', short: 'CON' },
    int: { name: 'Intelligence', short: 'INT' },
    wis: { name: 'Wisdom', short: 'WIS' },
    cha: { name: 'Charisma', short: 'CHA' },
  } satisfies Record<Ability, { name: string; short: string }>,
  worlds: 'Worlds',
  worldsCurrent: 'you are here',
  /** The presence label of a shared (multiplayer) world. */
  presence: {
    connecting: 'Looking for other visitors…',
    alone: 'You are the only visitor here',
    others: (n: number): string => (n === 1 ? '1 other visitor here' : `${n} other visitors here`),
    offline: 'No connection: you see no other visitors',
    version: 'The game has changed: reload the page to see other visitors',
    full: 'The world is full: you are alone in your copy',
    busy: 'Too many open tabs: this one is alone',
    world: 'This world is not shared now',
    account: 'Sign in to see other visitors',
    elsewhere: 'You signed in on another device',
  },
} as const;
